@revisao_HostAddress = http://localhost:5189

### Criar novo usuário (signup)
POST {{revisao_HostAddress}}/api/User/signup
Content-Type: application/json

{
  "email": "Notadmin@example.com",
  "password": "StrongPassword123",
  "Role": 1
}


###

### Login de usuário
POST {{revisao_HostAddress}}/api/User/login
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "StrongPassword123"
}

###

### Listar todos os usuários
GET {{revisao_HostAddress}}/api/User/list
Content-Type: application/json

###

### Listar usuário por ID
GET {{revisao_HostAddress}}/api/User/list/1
Content-Type: application/json

###

### Atualizar usuário
PUT {{revisao_HostAddress}}/api/User/update/1
Content-Type: application/json

{
  "id": 1,
  "email": "usuario@atualizado.com",
  "password": "novaSenha",
  "role": 0
}

###

### Deletar usuário
DELETE {{revisao_HostAddress}}/api/User/delete/1
Content-Type: application/json
